"use client";

import React, { useState, useRef } from "react";
import { FileText, Trash2, Download, Eye, EyeOff, Wand2, Copy, Check, Lock, Loader2 } from "lucide-react";
import { SecureNote, UploadCard } from "@/components/tools/upload-card";
import { loadPdfjs } from "@/lib/pdf-libs";
import { errorMessage } from "@/lib/errors";
import { downloadBlob } from "@/lib/download";
import { useCancellableRun, wasCancelled } from "@/hooks/useCancellableRun";

export default function ProtectPdfPage() {
    const [file, setFile] = useState<{ name: string; size: string; rawFile: File } | null>(null);
    const { begin, cancel } = useCancellableRun();
    const [password, setPassword] = useState("");
    const [confirmPassword, setConfirmPassword] = useState("");
    const [showPassword, setShowPassword] = useState(false);
    const [processing, setProcessing] = useState(false);
    const [done, setDone] = useState(false);
    const [copied, setCopied] = useState(false);
    const [autoGenerated, setAutoGenerated] = useState(false);
    const [numPages, setNumPages] = useState<number>(0);
    const [error, setError] = useState("");

    const canvasRefs = useRef<HTMLCanvasElement[]>([]);

    const formatSize = (bytes: number) => {
        if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`;
        return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
    };

    const handleFile = async (fileList: FileList | null) => {
        if (!fileList || fileList.length === 0) return;
        const f = fileList[0];
        if (f.type !== "application/pdf") {
            // Was a silent return, so picking a .docx looked like nothing happened.
            setError("Please select a valid PDF document.");
            return;
        }

        setFile({ name: f.name, size: formatSize(f.size), rawFile: f });
        setDone(false);
        setError("");

        try {
            const arrayBuffer = await f.arrayBuffer();
            const pdfjsLib = await loadPdfjs();
            const loadingTask = pdfjsLib.getDocument({ data: arrayBuffer });
            const pdfDoc = await loadingTask.promise;
            setNumPages(pdfDoc.numPages);

            setTimeout(async () => {
                for (let i = 1; i <= pdfDoc.numPages; i++) {
                    const page = await pdfDoc.getPage(i);
                    const viewport = page.getViewport({ scale: 1.0 });
                    const canvas = canvasRefs.current[i - 1];
                    if (canvas) {
                        const context = canvas.getContext("2d");
                        canvas.height = viewport.height;
                        canvas.width = viewport.width;
                        if (context) {
                            await page.render({ canvasContext: context, viewport }).promise;
                        }
                    }
                }
            }, 100);
        } catch {
            setError("Failed to load PDF preview.");
        }
    };

    const clearFile = () => {
    // Removing the file stops whatever it was being used for.
    cancel();
        setFile(null);
        setDone(false);
        setNumPages(0);
        setError("");
    };

    const passwordsMatch = password.length > 0 && password === confirmPassword;

    const generatePassword = () => {
        const chars = "ABCDEFGHJKMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789!@#$%&*";
        let result = "";
        for (let i = 0; i < 14; i++) {
            result += chars[Math.floor(Math.random() * chars.length)];
        }
        setPassword(result);
        setConfirmPassword(result);
        setShowPassword(true);
        setAutoGenerated(true);
        setCopied(false);
    };

    const handleCopy = async () => {
        if (!password) return;
        try {
            await navigator.clipboard.writeText(password);
            setCopied(true);
            setTimeout(() => setCopied(false), 1500);
        } catch {
            // Clipboard access is blocked on some mobile browsers outside a
            // secure context; say so rather than silently doing nothing.
            setError("Could not copy automatically. Select the password and copy it manually.");
        }
    };

    const handleProtect = async (e: React.FormEvent) => {
      const signal = begin();
        e.preventDefault();
        if (!file) {
            setError("Please select a PDF file.");
            return;
        }
        if (!password) {
            setError("Please enter a password.");
            return;
        }
        if (!passwordsMatch) {
            setError("Passwords do not match.");
            return;
        }

        setProcessing(true);
        setError("");

        const formData = new FormData();
        formData.append("file", file.rawFile);
        formData.append("password", password);

        try {
            const res = await fetch("/api/protect-pdf", {
                method: "POST",
                body: formData, signal });

            if (!res.ok) {
                const data = await res.json();
                throw new Error(data.error || "Failed to protect PDF");
            }

            const blob = await res.blob();
            downloadBlob(blob, `${file.name.replace(/\.[^/.]+$/, "")}-protected.pdf`);
            setDone(true);
        } catch (err) {
      if (wasCancelled(err, signal)) return;
            setError(errorMessage(err, "An unexpected error occurred."));
        } finally {
            setProcessing(false);
        }
    };

    return (
        <div className="max-w-2xl mx-auto w-full px-4 sm:px-6 py-6 sm:py-10">
            {/* Header — one copy, outside the branches. It used to be
                duplicated in both the empty and the configured state. */}
            <div className="text-center mb-6 sm:mb-8">
                <div className="w-12 h-12 sm:w-14 sm:h-14 mx-auto rounded-2xl bg-accent border border-primary/20 flex items-center justify-center mb-3 text-primary">
                    <Lock className="w-6 h-6 sm:w-7 sm:h-7" />
                </div>
                <h1 className="text-xl sm:text-2xl lg:text-3xl font-extrabold text-fg tracking-tight px-2">
                    Protect PDF
                </h1>
                <p className="text-muted text-[13px] sm:text-sm mt-1.5 max-w-xs sm:max-w-lg mx-auto leading-relaxed">
                    {file
                        ? "Set a password so only people you choose can open this file."
                        : "Add a password so only people you choose can open this file."}
                </p>
            </div>

            {!file ? (
                <div className="space-y-4">
                    <UploadCard
                        onFiles={handleFile}
                        title="Click to browse or drag & drop a PDF"
                        hint="Supports text documents and reports"
                    />

                    {error && (
                        <div className="p-3.5 sm:p-4 rounded-xl bg-red-500/10 border border-red-500/30 text-red-500 text-[13px] sm:text-sm font-semibold text-center">
                            {error}
                        </div>
                    )}
                </div>
            ) : (
                <form onSubmit={handleProtect} className="space-y-4 sm:space-y-6">
                    {/* File summary */}
                    <div className="bg-card border border-card rounded-2xl p-4 sm:p-5 shadow-sm flex items-center justify-between gap-3 sm:gap-4">
                        <div className="flex items-center gap-3 sm:gap-3.5 min-w-0">
                            <div className="w-10 h-10 sm:w-12 sm:h-12 rounded-xl bg-primary/10 text-primary flex items-center justify-center shrink-0 border border-primary/20">
                                <FileText className="w-5 h-5 sm:w-6 sm:h-6" />
                            </div>
                            <div className="min-w-0">
                                <p className="text-fg text-[13px] sm:text-sm font-bold truncate">{file.name}</p>
                                <p className="text-muted text-[11px] sm:text-xs mt-0.5 truncate">
                                    Size: <strong className="text-fg">{file.size}</strong>
                                    {numPages > 0 && <> • {numPages} {numPages === 1 ? "Page" : "Pages"}</>}
                                </p>
                            </div>
                        </div>
                        <button
                            type="button"
                            onClick={clearFile}
                            className="p-2 sm:p-2.5 rounded-xl bg-[var(--secondary)] text-[var(--primary)] hover:bg-[var(--primary)] hover:text-[var(--primary-foreground)] transition-colors shrink-0"
                            title="Remove file"
                        >
                            <Trash2 className="w-4 h-4 sm:w-[18px] sm:h-[18px]" />
                        </button>
                    </div>

                    {/* Preview */}
                    {numPages > 0 && (
                        <div className="space-y-2 bg-card p-3 sm:p-4 rounded-2xl border border-card shadow-sm">
                            <span className="text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-muted">
                                Document Preview ({numPages} {numPages === 1 ? "Page" : "Pages"})
                            </span>
                            <div className="space-y-3 sm:space-y-4 max-h-48 sm:max-h-56 overflow-y-auto flex flex-col items-center p-2 rounded-lg bg-muted border border-card">
                                {Array.from({ length: numPages }, (_, i) => (
                                    <div key={i} className="shadow-lg bg-white p-1.5 rounded max-w-full">
                                        <p className="text-[10px] text-gray-500 mb-1 text-center font-medium">
                                            Page {i + 1}
                                        </p>
                                        <canvas
                                            ref={(el) => {
                                                if (el) canvasRefs.current[i] = el;
                                            }}
                                            className="max-h-40 sm:max-h-48 max-w-full object-contain rounded"
                                        />
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Password */}
                    <div className="bg-card border border-card rounded-2xl p-4 sm:p-5 shadow-sm space-y-4">
                        <div>
                            <div className="flex flex-wrap items-center justify-between gap-x-2 gap-y-1 mb-2">
                                <label className="text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-muted">
                                    Password
                                </label>
                                <button
                                    type="button"
                                    onClick={generatePassword}
                                    className="inline-flex items-center gap-1 text-[11px] sm:text-xs font-medium text-[var(--primary)] hover:text-[var(--primary-hover)] hover:underline"
                                >
                                    <Wand2 size={13} className="shrink-0" />
                                    Generate strong password
                                </button>
                            </div>
                            <div className="relative">
                                <input
                                    type={showPassword ? "text" : "password"}
                                    value={password}
                                    onChange={(e) => {
                                        setPassword(e.target.value);
                                        setAutoGenerated(false);
                                        setCopied(false);
                                    }}
                                    placeholder="Enter password"
                                    autoComplete="new-password"
                                    className="w-full bg-card border border-card rounded-xl px-4 py-3.5 sm:py-3 pr-20 text-base sm:text-sm text-fg focus:outline-none focus:border-primary"
                                />
                                <div className="absolute right-3 top-1/2 -translate-y-1/2 flex items-center gap-2.5">
                                    {autoGenerated && password.length > 0 && (
                                        <button
                                            type="button"
                                            onClick={handleCopy}
                                            className="text-[var(--primary)] hover:text-[var(--primary-hover)] p-0.5"
                                            title="Copy password"
                                            aria-label="Copy password"
                                        >
                                            {copied ? (
                                                <Check size={16} className="text-emerald-600 dark:text-emerald-400" />
                                            ) : (
                                                <Copy size={16} />
                                            )}
                                        </button>
                                    )}
                                    <button
                                        type="button"
                                        onClick={() => setShowPassword(!showPassword)}
                                        aria-label={showPassword ? "Hide password" : "Show password"}
                                        className="text-[var(--primary)] hover:text-[var(--primary-hover)] p-0.5"
                                    >
                                        {showPassword ? <EyeOff size={16} /> : <Eye size={16} />}
                                    </button>
                                </div>
                            </div>
                            {autoGenerated && (
                                <p className="text-[11px] sm:text-xs text-muted mt-1.5 leading-relaxed">
                                    We generated this password for you — copy and save it before continuing.
                                </p>
                            )}
                        </div>

                        <div>
                            <label className="block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-muted mb-2">
                                Confirm Password
                            </label>
                            <input
                                type={showPassword ? "text" : "password"}
                                value={confirmPassword}
                                onChange={(e) => {
                                    setConfirmPassword(e.target.value);
                                    setAutoGenerated(false);
                                }}
                                placeholder="Re-enter password"
                                autoComplete="new-password"
                                className="w-full bg-card border border-card rounded-xl px-4 py-3.5 sm:py-3 text-base sm:text-sm text-fg focus:outline-none focus:border-primary"
                            />
                            {confirmPassword.length > 0 && !passwordsMatch && (
                                <p className="text-[11px] sm:text-xs text-red-600 dark:text-red-400 mt-1.5">
                                    Passwords do not match
                                </p>
                            )}
                        </div>
                    </div>

                    {error && (
                        <div className="p-3.5 sm:p-4 rounded-xl bg-red-500/10 border border-red-500/30 text-red-500 text-[13px] sm:text-sm font-semibold text-center">
                            {error}
                        </div>
                    )}

                    {/* Actions */}
                    <div className="flex flex-col-reverse sm:flex-row sm:items-center gap-3 sm:gap-4 pt-1 sm:pt-2">
                        <button
                            type="button"
                            onClick={clearFile}
                            className="w-full sm:w-auto py-3.5 sm:py-4 px-6 sm:px-8 rounded-2xl border border-[var(--primary)] text-[var(--primary)] hover:bg-[var(--secondary)] font-bold text-sm transition-colors"
                        >
                            Select Different File
                        </button>
                        <button
                            type="submit"
                            disabled={processing || !passwordsMatch || !file}
                            className="w-full sm:flex-1 py-3.5 sm:py-4 px-4 rounded-2xl bg-[var(--primary)] border border-[var(--primary)] hover:bg-[var(--primary-hover)] hover:border-[var(--primary-hover)] text-[var(--primary-foreground)] font-bold text-sm sm:text-base shadow-lg disabled:opacity-50 flex items-center justify-center gap-2 transition-all"
                        >
                            {processing ? (
                                <>
                                    <Loader2 className="animate-spin shrink-0" size={18} />
                                    Protecting PDF...
                                </>
                            ) : (
                                <>
                                    <Download className="shrink-0" size={18} />
                                    {done ? "Download Protected PDF Again" : "Protect and Download PDF"}
                                </>
                            )}
                        </button>
                    </div>

                </form>
            )}

            <SecureNote />
        </div>
    );
}